# Generated by Django 5.1 on 2026-03-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='video',
            name='fetch_from_youtube',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='important_topics',
            field=models.TextField(blank=True, help_text='Comma separated topics'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='source',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], default='youtube', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Numerical', 'Numerical')], default='Theory', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url_input',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='videos.category')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='videos.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Rich text / markdown supported')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='notes/pdfs/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated or JSON', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='videos.video')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='videos.subject')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.subject'),
        ),
    ]
