# Generated by Django 5.1 on 2026-03-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_category_remove_video_category_remove_video_video_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
