# Generated by Django 5.1 on 2026-03-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_is_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.subject'),
        ),
    ]
