# Generated by Django 5.1 on 2026-03-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_type', models.CharField(default='youtube', max_length=50)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('videos_added', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
