# Generated by Django 5.1 on 2026-03-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_youtube_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='video',
            name='quick_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='roadmap',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
