# Generated by Django 5.1 on 2026-03-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='topic_flow',
            field=models.TextField(blank=True, help_text='Comma-separated topics (overrides description auto-generation)'),
        ),
    ]
