# Generated by Django 5.1 on 2026-04-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_reel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='reel_thumbnails/'),
        ),
    ]
