# Generated by Django 5.1 on 2026-04-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_rename_link_reel_video_url_category_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
