# Generated by Django 5.1 on 2026-06-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_category_description_subcategory_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['-created_at'], name='videos_reel_created_039a08_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_published'], name='videos_vide_is_publ_293310_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_important'], name='videos_vide_is_impo_69f89c_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-created_at'], name='videos_vide_created_1f1e45_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['subject', 'is_published'], name='videos_vide_subject_2ab2fd_idx'),
        ),
    ]
