"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

import sys

# Optional production dependencies
try:
    import dj_database_url
except ImportError:
    dj_database_url = None
    print("WARNING: dj_database_url is not installed. Database configuration might fall back to SQLite.", file=sys.stderr)

try:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
except ImportError:
    sentry_sdk = None
    DjangoIntegration = None
    print("INFO: sentry_sdk is not installed. Sentry monitoring is disabled.", file=sys.stderr)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ─── Environment Configuration ──────────────────────────────────────
ENVIRONMENT = os.getenv("ENVIRONMENT", "local")

if ENVIRONMENT == "production":
    load_dotenv(os.path.join(BASE_DIR, '.env.production'))
else:
    load_dotenv(os.path.join(BASE_DIR, '.env'))

# Initialize Sentry if DSN is provided
SENTRY_DSN = os.getenv("SENTRY_DSN")
if SENTRY_DSN and sentry_sdk:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()] if DjangoIntegration else [],
        traces_sample_rate=1.0,
        send_default_pii=True,
    )


# ─── Core Security ──────────────────────────────────────────────────
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-replace-this-in-prod')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')

# ALLOWED_HOSTS supports multiple domains via environment variable (comma-separated)
raw_hosts = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost')
# Strip any outer brackets, quotes, or whitespace that could be copy-pasted in env vars
raw_hosts = raw_hosts.strip("[]'\" ")
ALLOWED_HOSTS = [host.strip() for host in raw_hosts.split(',') if host.strip()]



# ─── Application Definition ─────────────────────────────────────────

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'videos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES_DIR_FRONTEND = BASE_DIR.parent / 'frontend' / 'dist'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR_FRONTEND] if TEMPLATES_DIR_FRONTEND.exists() else [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'backend.wsgi.application'


# ─── Database ────────────────────────────────────────────────────────

# Production Avian/RDS/Neon PostgreSQL vs Local SQLite
DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    # Neon PostgreSQL requires sslmode=require in the connection URL itself.
    # Append it to the query parameters if it is not already present.
    if "sslmode=" not in DATABASE_URL:
        if "?" in DATABASE_URL:
            DATABASE_URL += "&sslmode=require"
        else:
            DATABASE_URL += "?sslmode=require"

if DATABASE_URL and dj_database_url:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=False,
        ),
        'sqlite': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
elif os.getenv("DB_NAME"):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': 'require',
            },
            'CONN_MAX_AGE': 600,
        },
        'sqlite': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    # Failsafe: Fallback to SQLite if credentials are missing (local development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }



# ─── Password Validation ────────────────────────────────────────────

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ─── Internationalization ────────────────────────────────────────────

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ─── Static & Media Files ───────────────────────────────────────────
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_FILES_DIRS_FRONTEND = BASE_DIR.parent / 'frontend' / 'dist'
STATICFILES_DIRS = [
    STATIC_FILES_DIRS_FRONTEND,
] if STATIC_FILES_DIRS_FRONTEND.exists() else []

# Use WhiteNoise's CompressedStaticFilesStorage to prevent crashes when manifest entries are missing
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'


# ─── Media Storage (Cloudinary for Production) ──────────────────────
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME')
if CLOUDINARY_CLOUD_NAME:
    try:
        import cloudinary
        import cloudinary_storage
        # django-cloudinary-storage requires it to be inserted before staticfiles
        if 'cloudinary_storage' not in INSTALLED_APPS:
            staticfiles_idx = INSTALLED_APPS.index('django.contrib.staticfiles')
            INSTALLED_APPS.insert(staticfiles_idx, 'cloudinary_storage')
        if 'cloudinary' not in INSTALLED_APPS:
            INSTALLED_APPS.append('cloudinary')
            
        DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
        CLOUDINARY_STORAGE = {
            'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
            'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
            'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
        }
    except ImportError as e:
        print(f"WARNING: Cloudinary is configured but integration libraries are missing: {e}", file=sys.stderr)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ─── Default Primary Key ────────────────────────────────────────────

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ─── CORS & CSRF ────────────────────────────────────────────────────

CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in dev
CORS_ALLOW_CREDENTIALS = True

# Production domains from environment
raw_cors_origins = os.getenv('CORS_ALLOWED_ORIGINS', '')
# Strip any outer brackets, quotes, or whitespace that could be copy-pasted in env vars
raw_cors_origins = raw_cors_origins.strip("[]'\" ")
EXTRA_ORIGINS = [origin.strip() for origin in raw_cors_origins.split(',') if origin.strip()]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
] + EXTRA_ORIGINS

# CSRF Trusted Origins - Ensure https is used for production
raw_csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
# Strip any outer brackets, quotes, or whitespace that could be copy-pasted in env vars
raw_csrf_origins = raw_csrf_origins.strip("[]'\" ")
CSRF_TRUST_URLS = [url.strip() for url in raw_csrf_origins.split(',') if url.strip()]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
] + CSRF_TRUST_URLS



# ─── Caching ────────────────────────────────────────────────────────

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "concepts-in-5-cache",
    }
}


# ─── Cookie Security ────────────────────────────────────────────────

SESSION_COOKIE_HTTPONLY = True       # Prevent JS access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'     # CSRF protection for session cookie
CSRF_COOKIE_HTTPONLY = False         # Must be False so axios can read CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'        # CSRF protection for CSRF cookie

# Production HTTPS settings - enabled dynamically in non-debug mode
IS_RENDER = os.getenv("RENDER", "false").lower() == "true"

# Disable SECURE_SSL_REDIRECT on Render or in development to prevent infinite redirect loops
if IS_RENDER or DEBUG:
    SECURE_SSL_REDIRECT = False
else:
    SECURE_SSL_REDIRECT = True

# Always trust Render's SSL terminating reverse proxy for HTTPS detection
if IS_RENDER:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Set proxy SSL header generally if not debug and not already set
    if not IS_RENDER:
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



# ─── Django REST Framework ───────────────────────────────────────────

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 6,
    'EXCEPTION_HANDLER': 'videos.exceptions.custom_exception_handler',
}


# ─── YouTube API Settings ───────────────────────────────────────────

YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")
YOUTUBE_CHANNEL_ID = os.getenv("YOUTUBE_CHANNEL_ID")


# ─── Logging ────────────────────────────────────────────────────────

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'videos': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

# Add file-based logging only when developing locally
if DEBUG and not os.getenv("RENDER"):
    # Ensure logs directory exists
    logs_dir = BASE_DIR / 'logs'
    os.makedirs(logs_dir, exist_ok=True)
    
    LOGGING['handlers']['file_error'] = {
        'class': 'logging.FileHandler',
        'filename': logs_dir / 'errors.log',
        'formatter': 'verbose',
        'level': 'ERROR',
    }
    LOGGING['handlers']['file_info'] = {
        'class': 'logging.FileHandler',
        'filename': logs_dir / 'actions.log',
        'formatter': 'verbose',
        'level': 'INFO',
    }
    LOGGING['loggers']['videos']['handlers'].extend(['file_error', 'file_info'])
    LOGGING['loggers']['django']['handlers'].append('file_error')
